name: Generate HTML Index

on:
  push:
    paths:
      - 'htmls/**.html'
      - '.github/workflows/generate-index.yml'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Generate index.html and filelist.json
      run: python htmls/generate_index.py

    - name: Commit and push if changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add htmls/index.html htmls/filelist.json
        git diff --cached --quiet || git commit -m "Auto-generate index.html and filelist.json"
        git push
